services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiout_test_backend_api
    ports:
      - "127.0.0.1:${API_SERVER_PORT}:8000"
    command: >
      sh -c "
      poetry run python manage.py collectstatic --noinput &&
      poetry run python manage.py migrate &&
      poetry run python create_superuser.py &&
      poetry run python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped
