# Generated by Django 5.1.5 on 2025-10-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Введите имя", max_length=50),
                ),
                (
                    "middle_name",
                    models.CharField(help_text="Введите фамилию", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество при наличии",
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(help_text="email", max_length=255)),
                (
                    "position",
                    models.CharField(blank=True, help_text="Должность", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("hired_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
