# Generated by Django 5.2.7 on 2025-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0002_alter_worker_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.EmailField(
                db_index=True, help_text="email", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="last_name",
            field=models.CharField(help_text="Введите фамилию", max_length=50),
        ),
        migrations.AlterField(
            model_name="worker",
            name="middle_name",
            field=models.CharField(
                blank=True, help_text="Введите отчество при наличии", max_length=50
            ),
        ),
    ]
